name: Build and deploy project

on:
  push:
    branches:
      - main

jobs:
  buildWebGL:
    name: Build for WebGL
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          lfs: true

      - name: Restore Library cache
        uses: actions/cache@v3.3.3
        with:
          path: Space-Fox.Unity/Library
          key: Library-WebGL
          restore-keys: Library-

      - name: Build
        uses: game-ci/unity-builder@v4.1.3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: Space-Fox.Unity/
          targetPlatform: WebGL

      - name: Upload a build artifact
        uses: actions/upload-artifact@v4.1.0
        with:
          name: Build-WebGL
          path: build/WebGL

  deployPages:
    needs: buildWebGL
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Download artifact
        uses: actions/download-artifact@v4.1.1
        with:
          name: Build-WebGL
          path: build
            
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: build/WebGL
